const teams=["Meem Police","FC Maavadibe","FC Karaa","Muli Blues","Blackout 5","Triple T","Smashers FC"];
const teamLogos={"Meem Police":"assets/meemu_police_club_transparent.webp","FC Maavadibe":"assets/fc_maavadibe_transparent.webp","FC Karaa":"assets/karaa_transparent.webp","Muli Blues":"assets/muli_blues_fc_transparent.webp","Blackout 5":"assets/blackoutfive_transparent.webp","Triple T":"assets/triple_t_transparent.webp","Smashers FC":"assets/smashers_fc_transparent.webp"};
const matches=[
{id:1,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 1",time:"20:45 – 21:00",home:"FC Maavadibe",away:"Smashers FC"},
{id:2,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 1",time:"21:05 – 21:20",home:"FC Karaa",away:"Triple T"},
{id:3,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 1",time:"21:25 – 21:40",home:"Muli Blues",away:"Blackout 5"},
{id:4,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 2",time:"21:50 – 22:05",home:"Meem Police",away:"Smashers FC"},
{id:5,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 2",time:"22:10 – 22:25",home:"FC Maavadibe",away:"Blackout 5"},
{id:6,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 2",time:"22:30 – 22:45",home:"FC Karaa",away:"Muli Blues"},
{id:7,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 3",time:"22:55 – 23:10",home:"Meem Police",away:"Triple T"},
{id:8,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 3",time:"23:15 – 23:30",home:"Smashers FC",away:"Blackout 5"},
{id:9,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 3",time:"23:35 – 23:50",home:"FC Maavadibe",away:"FC Karaa"},
{id:10,day:"Day 2 — Thursday, 28 May 2026",round:"Round 4",time:"20:15 – 20:30",home:"Meem Police",away:"Blackout 5"},
{id:11,day:"Day 2 — Thursday, 28 May 2026",round:"Round 4",time:"20:35 – 20:50",home:"Triple T",away:"Muli Blues"},
{id:12,day:"Day 2 — Thursday, 28 May 2026",round:"Round 4",time:"20:55 – 21:10",home:"Smashers FC",away:"FC Karaa"},
{id:13,day:"Day 2 — Thursday, 28 May 2026",round:"Round 5",time:"21:20 – 21:35",home:"Meem Police",away:"Muli Blues"},
{id:14,day:"Day 2 — Thursday, 28 May 2026",round:"Round 5",time:"21:40 – 21:55",home:"Blackout 5",away:"FC Karaa"},
{id:15,day:"Day 2 — Thursday, 28 May 2026",round:"Round 5",time:"22:00 – 22:15",home:"Triple T",away:"FC Maavadibe"},
{id:16,day:"Day 2 — Thursday, 28 May 2026",round:"Round 6",time:"22:25 – 22:40",home:"Meem Police",away:"FC Karaa"},
{id:17,day:"Day 2 — Thursday, 28 May 2026",round:"Round 6",time:"22:45 – 23:00",home:"Muli Blues",away:"FC Maavadibe"},
{id:18,day:"Day 2 — Thursday, 28 May 2026",round:"Round 6",time:"23:05 – 23:20",home:"Triple T",away:"Smashers FC"},
{id:19,day:"Day 2 — Thursday, 28 May 2026",round:"Round 7",time:"23:30 – 23:45",home:"Meem Police",away:"FC Maavadibe"},
{id:20,day:"Day 2 — Thursday, 28 May 2026",round:"Round 7",time:"23:50 – 00:05",home:"Muli Blues",away:"Smashers FC"},
{id:21,day:"Day 2 — Thursday, 28 May 2026",round:"Round 7",time:"00:10 – 00:25",home:"Blackout 5",away:"Triple T"},
{id:22,day:"Grand Final — Friday, 29 May 2026",round:"Grand Final",time:"After league stage",home:"1st Place",away:"2nd Place",isFinal:true}
];
const leagueMatches=matches.filter(m=>!m.isFinal);
const key="goal-diggers-cup-2026-scores";
const admin=new URLSearchParams(location.search).get("admin")==="1";
let activeFilter="all";
const openDays={};
function scores(){try{return JSON.parse(localStorage.getItem(key))||{}}catch{return{}}}
function num(v){if(v===""||v==null)return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}
function initials(n){return n.split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase().replace("5","5")}
function teamMark(team){const logo=teamLogos[team];return logo?`<img class="team-logo" src="${logo}" alt="${team} logo" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid';"><div class="team-badge fallback-badge" style="display:none">${initials(team)}</div>`:`<div class="team-badge">${initials(team)}</div>`}
function dayDate(m){return m.day.includes("28 May")?"2026-05-28":m.day.includes("29 May")?"2026-05-29":"2026-05-27"}
function dayKey(day){return day.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
function shortDay(day){return day.replace("Wednesday, ","Wed ").replace("Thursday, ","Thu ").replace("Friday, ","Fri ")}
function matchTimes(m){if(!m.time.includes("–"))return null;const [startRaw,endRaw]=m.time.split("–").map(x=>x.trim());let startDate=dayDate(m),endDate=dayDate(m);const [sh,sm]=startRaw.split(":").map(Number),[eh,em]=endRaw.split(":").map(Number);if(!Number.isFinite(sh)||!Number.isFinite(sm)||!Number.isFinite(eh)||!Number.isFinite(em))return null;if(eh<sh||(eh===sh&&em<sm)){const d=new Date(`${endDate}T00:00:00+05:00`);d.setDate(d.getDate()+1);endDate=d.toISOString().slice(0,10)}return{start:new Date(`${startDate}T${startRaw}:00+05:00`),end:new Date(`${endDate}T${endRaw}:00+05:00`)}}
function clock(ms){const total=Math.max(0,Math.ceil(ms/1000));const m=String(Math.floor(total/60)).padStart(2,"0");const s=String(total%60).padStart(2,"0");return`${m}:${s}`}
function liveTimer(m){const t=matchTimes(m);if(!t)return"Live";const now=new Date();return`${clock(t.end-now)} left`}
function isDone(m){const r=scores()[m.id]||{};return num(r.home)!==null&&num(r.away)!==null}
function liveMatch(){const now=new Date();return matches.find(m=>{const t=matchTimes(m);return t&&now>=t.start&&now<=t.end&&!isDone(m)})}
function nextUnplayed(){return matches.find(m=>!isDone(m))}
function table(){const s=scores();const t=Object.fromEntries(teams.map(team=>[team,{team,played:0,won:0,drawn:0,lost:0,gf:0,ga:0,gd:0,points:0}]));leagueMatches.forEach(m=>{const r=s[m.id]||{};const h=num(r.home),a=num(r.away);if(h===null||a===null)return;const H=t[m.home],A=t[m.away];H.played++;A.played++;H.gf+=h;H.ga+=a;A.gf+=a;A.ga+=h;if(h>a){H.won++;H.points+=3;A.lost++}else if(h<a){A.won++;A.points+=3;H.lost++}else{H.drawn++;A.drawn++;H.points++;A.points++}});return Object.values(t).map(r=>({...r,gd:r.gf-r.ga})).sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team))}
function updateMatchCards(){const done=leagueMatches.filter(m=>isDone(m)).length;const current=liveMatch();const next=nextUnplayed();document.getElementById("playedCount").textContent=`${done} / ${leagueMatches.length}`;document.getElementById("currentMatchTitle").textContent=current?`${current.home} vs ${current.away}`:"No live match";document.getElementById("currentMatchMeta").textContent=current?`Live • ${liveTimer(current)} • ${current.round}`:next?"Next match below":"Tournament complete";document.getElementById("nextMatchTitle").textContent=next?`${next.home} vs ${next.away}`:"Tournament complete";document.getElementById("nextMatchMeta").textContent=next?`${next.time} • ${next.round}`:"Thanks for following"}
function renderTable(){const rows=table();const el=document.getElementById("standingsList");if(el)el.innerHTML=rows.map((r,i)=>`<div class="league-row ${i<2?'top-two':''}"><span>${i+1}</span><div class="team-cell">${teamMark(r.team)}<strong>${r.team}</strong></div><span>${r.played}</span><span>${r.won}</span><span>${r.gd>0?'+':''}${r.gd}</span><b>${r.points}</b></div>`).join("");updateMatchCards()}
function matchRow(m,s,liveNow){const r=s[m.id]||{};const h=num(r.home),a=num(r.away),done=h!==null&&a!==null;const live=liveNow?.id===m.id;const score=admin?`<div class="admin-fields"><input class="score-input" type="number" min="0" data-match="${m.id}" data-side="home" value="${r.home??''}"><span>-</span><input class="score-input" type="number" min="0" data-match="${m.id}" data-side="away" value="${r.away??''}"></div>`:`<div class="score-display">${done?`${h} - ${a}`:'vs'}</div>`;const matchId=m.isFinal?'FINAL':`#${m.id}`;return`<article class="match-card ${m.isFinal?'final-match-card':''}"><div class="match-meta">${matchId}<br>${m.time}</div><div class="team-name">${m.home}</div>${score}<div class="team-name team-away">${m.away}</div><div class="status-pill ${done?'completed':live?'live':m.isFinal?'final-status':''}">${done?'FT':live?liveTimer(m):m.isFinal?'Final':'Upcoming'}</div></article>`}
function renderMatches(){const s=scores();const liveNow=liveMatch();const visible=matches.filter(m=>{const done=isDone(m);return !(activeFilter==="completed"&&!done||activeFilter==="upcoming"&&done)});const groups=[];visible.forEach(m=>{let g=groups.find(x=>x.day===m.day);if(!g){g={day:m.day,matches:[]};groups.push(g)}g.matches.push(m)});let html="";groups.forEach((g,i)=>{const key=dayKey(g.day);if(openDays[key]===undefined)openDays[key]=i===0;const expanded=openDays[key];let round="";let body="";g.matches.forEach(m=>{if(m.round!==round){round=m.round;body+=`<div class="round-title ${m.isFinal?'final-round-title':''}">${m.round}</div>`}body+=matchRow(m,s,liveNow)});const count=g.matches.length;html+=`<section class="fixture-day ${expanded?'open':'closed'}"><button class="day-toggle" type="button" data-day="${key}" aria-expanded="${expanded}"><span>${shortDay(g.day)}</span><small>${count} ${count===1?'match':'matches'}</small><b>${expanded?'−':'+'}</b></button><div class="day-fixtures" ${expanded?'':'hidden'}>${body}</div></section>`});document.getElementById("scheduleList").innerHTML=html||`<div class="empty-state">No matches found.</div>`;document.querySelectorAll(".day-toggle").forEach(btn=>btn.addEventListener("click",()=>{openDays[btn.dataset.day]=!openDays[btn.dataset.day];renderMatches()}));document.querySelectorAll(".score-input").forEach(input=>input.addEventListener("input",e=>{const s=scores();const id=e.target.dataset.match,side=e.target.dataset.side;s[id]=s[id]||{};s[id][side]=e.target.value;if((s[id].home??"")===""&&(s[id].away??"")==="")delete s[id];localStorage.setItem(key,JSON.stringify(s));renderMatches();renderTable()}))}
function openTab(name){document.querySelectorAll(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===`panel-${name}`))}
document.querySelectorAll(".tab-btn").forEach(b=>b.addEventListener("click",()=>openTab(b.dataset.tab)));document.querySelectorAll(".filter-btn").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter-btn").forEach(x=>x.classList.toggle("active",x===b));renderMatches()}));const reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",()=>{localStorage.removeItem(key);renderMatches();renderTable()});document.getElementById("shareBtn").addEventListener("click",async()=>{if(navigator.share)await navigator.share({title:"Goal Diggers Cup 2026",url:location.href});else{await navigator.clipboard.writeText(location.href);alert("Page link copied")}});if(admin){const p=document.getElementById("adminPanel");if(p)p.hidden=false}renderMatches();renderTable();setInterval(()=>{renderMatches();updateMatchCards()},1000);