const teams=["Meem Police","FC Maavadibe","FC Karaa","Muli Blues","Blackout 5","Triple T","Smashers FC"];
const matches=[
{id:1,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 1",time:"20:45 – 21:00",home:"FC Maavadibe",away:"Smashers FC"},
{id:2,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 1",time:"21:05 – 21:20",home:"FC Karaa",away:"Triple T"},
{id:3,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 1",time:"21:25 – 21:40",home:"Muli Blues",away:"Blackout 5"},
{id:4,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 2",time:"21:50 – 22:05",home:"Meem Police",away:"Smashers FC"},
{id:5,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 2",time:"22:10 – 22:25",home:"FC Maavadibe",away:"Blackout 5"},
{id:6,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 2",time:"22:30 – 22:45",home:"FC Karaa",away:"Muli Blues"},
{id:7,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 3",time:"22:55 – 23:10",home:"Meem Police",away:"Triple T"},
{id:8,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 3",time:"23:15 – 23:30",home:"Smashers FC",away:"Blackout 5"},
{id:9,day:"Day 1 — Wednesday, 27 May 2026",round:"Round 3",time:"23:35 – 23:50",home:"FC Maavadibe",away:"FC Karaa"},
{id:10,day:"Day 2 — Thursday, 28 May 2026",round:"Round 4",time:"20:15 – 20:30",home:"Meem Police",away:"Blackout 5"},
{id:11,day:"Day 2 — Thursday, 28 May 2026",round:"Round 4",time:"20:35 – 20:50",home:"Triple T",away:"Muli Blues"},
{id:12,day:"Day 2 — Thursday, 28 May 2026",round:"Round 4",time:"20:55 – 21:10",home:"Smashers FC",away:"FC Karaa"},
{id:13,day:"Day 2 — Thursday, 28 May 2026",round:"Round 5",time:"21:20 – 21:35",home:"Meem Police",away:"Muli Blues"},
{id:14,day:"Day 2 — Thursday, 28 May 2026",round:"Round 5",time:"21:40 – 21:55",home:"Blackout 5",away:"FC Karaa"},
{id:15,day:"Day 2 — Thursday, 28 May 2026",round:"Round 5",time:"22:00 – 22:15",home:"Triple T",away:"FC Maavadibe"},
{id:16,day:"Day 2 — Thursday, 28 May 2026",round:"Round 6",time:"22:25 – 22:40",home:"Meem Police",away:"FC Karaa"},
{id:17,day:"Day 2 — Thursday, 28 May 2026",round:"Round 6",time:"22:45 – 23:00",home:"Muli Blues",away:"FC Maavadibe"},
{id:18,day:"Day 2 — Thursday, 28 May 2026",round:"Round 6",time:"23:05 – 23:20",home:"Triple T",away:"Smashers FC"},
{id:19,day:"Day 2 — Thursday, 28 May 2026",round:"Round 7",time:"23:30 – 23:45",home:"Meem Police",away:"FC Maavadibe"},
{id:20,day:"Day 2 — Thursday, 28 May 2026",round:"Round 7",time:"23:50 – 00:05",home:"Muli Blues",away:"Smashers FC"},
{id:21,day:"Day 2 — Thursday, 28 May 2026",round:"Round 7",time:"00:10 – 00:25",home:"Blackout 5",away:"Triple T"}
];
const key="goal-diggers-cup-2026-scores";const admin=new URLSearchParams(location.search).get("admin")==="1";let activeFilter="all";
function scores(){try{return JSON.parse(localStorage.getItem(key))||{}}catch{return{}}}
function num(v){if(v===""||v==null)return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}
function initials(n){return n.split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase().replace("5","5")}
function table(){const s=scores();const t=Object.fromEntries(teams.map(team=>[team,{team,played:0,won:0,drawn:0,lost:0,gf:0,ga:0,gd:0,points:0}]));matches.forEach(m=>{const r=s[m.id]||{};const h=num(r.home),a=num(r.away);if(h===null||a===null)return;const H=t[m.home],A=t[m.away];H.played++;A.played++;H.gf+=h;H.ga+=a;A.gf+=a;A.ga+=h;if(h>a){H.won++;H.points+=3;A.lost++}else if(h<a){A.won++;A.points+=3;H.lost++}else{H.drawn++;A.drawn++;H.points++;A.points++}});return Object.values(t).map(r=>({...r,gd:r.gf-r.ga})).sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team))}
function renderTable(){const rows=table();const el=document.getElementById("standingsList");if(el)el.innerHTML=rows.map((r,i)=>`<div class="league-row ${i<2?'top-two':''}"><span>${i+1}</span><div class="team-cell"><div class="team-badge">${initials(r.team)}</div><strong>${r.team}</strong></div><span>${r.played}</span><span>${r.won}</span><span>${r.gd>0?'+':''}${r.gd}</span><b>${r.points}</b></div>`).join("");const done=matches.filter(m=>{const r=scores()[m.id]||{};return num(r.home)!==null&&num(r.away)!==null}).length;const next=matches.find(m=>{const r=scores()[m.id]||{};return num(r.home)===null||num(r.away)===null});const leader=rows[0];document.getElementById("playedCount").textContent=`${done} / ${matches.length}`;document.getElementById("leaderName").textContent=done?leader.team:"—";document.getElementById("leaderMeta").textContent=done?`${leader.points} pts • GD ${leader.gd>0?'+':''}${leader.gd}`:"Scores pending";document.getElementById("nextMatchTitle").textContent=next?`${next.home} vs ${next.away}`:"League complete";document.getElementById("nextMatchMeta").textContent=next?`${next.time} • ${next.round}`:"Top 2 move to final"}
function renderMatches(){const s=scores();let day="",round="",html="";matches.forEach(m=>{const r=s[m.id]||{};const h=num(r.home),a=num(r.away),done=h!==null&&a!==null;const hide=activeFilter==="completed"&&!done||activeFilter==="upcoming"&&done;if(m.day!==day){day=m.day;round="";html+=`<div class="day-title">${m.day}</div>`}if(m.round!==round){round=m.round;html+=`<div class="round-title">${m.round}</div>`}const score=admin?`<div class="admin-fields"><input class="score-input" type="number" min="0" data-match="${m.id}" data-side="home" value="${r.home??''}"><span>-</span><input class="score-input" type="number" min="0" data-match="${m.id}" data-side="away" value="${r.away??''}"></div>`:`<div class="score-display">${done?`${h} - ${a}`:'vs'}</div>`;html+=`<article class="match-card ${hide?'hidden':''}"><div class="match-meta">#${m.id}<br>${m.time}</div><div class="team-name">${m.home}</div>${score}<div class="team-name team-away">${m.away}</div><div class="status-pill ${done?'completed':''}">${done?'FT':'Upcoming'}</div></article>`});document.getElementById("scheduleList").innerHTML=html;document.querySelectorAll(".score-input").forEach(input=>input.addEventListener("input",e=>{const s=scores();const id=e.target.dataset.match,side=e.target.dataset.side;s[id]=s[id]||{};s[id][side]=e.target.value;if((s[id].home??"")===""&&(s[id].away??"")==="")delete s[id];localStorage.setItem(key,JSON.stringify(s));renderMatches();renderTable()}))}
function openTab(name){document.querySelectorAll(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===`panel-${name}`))}
document.querySelectorAll(".tab-btn").forEach(b=>b.addEventListener("click",()=>openTab(b.dataset.tab)));document.querySelectorAll(".filter-btn").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter-btn").forEach(x=>x.classList.toggle("active",x===b));renderMatches()}));const reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",()=>{localStorage.removeItem(key);renderMatches();renderTable()});document.getElementById("shareBtn").addEventListener("click",async()=>{if(navigator.share)await navigator.share({title:"Goal Diggers Cup 2026",url:location.href});else{await navigator.clipboard.writeText(location.href);alert("Page link copied")}});if(admin){const p=document.getElementById("adminPanel");if(p)p.hidden=false}renderMatches();renderTable();